server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          search-paths: distancia,monolito,pagamento
          uri: https://github.com/xvhenom/SpringCloud_Calado1
